### ISSUE TITLE
Nano33 BLE

### ISSUE THREAD

**Issue by tvixen** [rricharz/i2c-sniffer-100kBaud-Arduino-Mega#5]
Hi Rene
Thanks for sharing your code.
Do you think you will be able to edit this so it would run on a Nano33 BLE.
As the Nano33 has a higer clock and more RAM + flash ram.

I know its not a AVR but a Arm Cortex-M4. But I had to ask.

Br Tim

**Comment by rricharz** [comment]
Unfortunately this project is closed. Modifying it for the Nano33 would be a major job.

**Comment by tvixen** [comment]
Oki... noted, thanks.
